# Generated by Django 6.0.1 on 2026-03-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeband',
            old_name='label',
            new_name='name',
        ),
    ]
