# Generated by Django 5.1.5 on 2026-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_casedocument_uploaded_by_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='detailed_status',
            field=models.CharField(blank=True, default='Awaiting Review', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='next_hearing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
