# Generated by Django 5.1.5 on 2026-01-29 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_case_detailed_status_case_next_hearing_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
