# Generated by Django 5.1.5 on 2026-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_message_hidden_for_message_is_attachment_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='quoted_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
