# Generated by Django 6.0.1 on 2026-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_interaction_quoted_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
