# Generated by Django 6.0.1 on 2026-05-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='is_deleted_everyone',
            field=models.BooleanField(default=False),
        ),
    ]
