# Generated by Django 6.0.1 on 2026-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_remove_lawyerprofile_languages_and_more'),
        ('users', '0003_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='languages',
            field=models.ManyToManyField(to='users.language'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
