# Generated by Django 6.0.1 on 2026-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyerprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='languages',
        ),
    ]
