# Generated by Django 5.1.5 on 2026-02-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_remove_lawyerprofile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='fee_band',
        ),
    ]
