# Generated by Django 6.0.1 on 2026-05-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_finalize_pgvector_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lawyerprofile',
            name='lawyer_emb_hnsw',
        ),
    ]
