# Generated by Django 6.0.1 on 2026-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_remove_lawyerprofile_lawyer_emb_hnsw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
