# Generated by Django 6.0.1 on 2026-05-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0011_remove_lawyerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
