# Generated by Django 6.0.1 on 2026-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_lawyerprofile_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Changes Requested')], default='pending', max_length=20),
        ),
    ]
